name: Infra-Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options: [dev, staging, prod]

      action:
        description: "Choose action"
        required: true
        type: choice
        options: [apply, destroy]

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ github.event.inputs.environment }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 60   # 👈 IMPORTANT
    
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: infra

    env:
      TF_IN_AUTOMATION: true

      TF_VAR_databricks_host: ${{ secrets.DATABRICKS_HOST }}
      TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::298493767003:role/reward-loyality-githubaction-role
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    # ---------------- INIT ----------------
    - name: Terraform Init
      run: |
        terraform init -upgrade \
          -backend-config="key=reward_loyality/${{ github.event.inputs.environment }}/terraform.tfstate"

    # ---------------- VALIDATE ----------------
    - name: Terraform Validate
      run: terraform validate

    # ---------------- FORMAT ----------------
    - name: Terraform Format Check
      run: terraform fmt -check

    # ---------------- PLAN ----------------
    - name: Terraform Plan
      shell: bash
      run: |
        set +e

        terraform plan \
          -var-file=environments/${{ github.event.inputs.environment }}.tfvars \
          -out=tfplan

        EXIT_CODE=$?

        echo "Terraform exit code: $EXIT_CODE"

        if [ "$EXIT_CODE" -eq 1 ]; then
          echo "❌ Terraform plan failed"
          exit 1
        fi

        echo "✅ Plan successful"

    # ---------------- APPLY ----------------
    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve tfplan

    # ---------------- DESTROY ----------------
    - name: Block Prod Destroy
      if: github.event.inputs.action == 'destroy' && github.event.inputs.environment == 'prod'
      run: |
        echo "❌ Destroy not allowed for PROD"
        exit 1

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: |
        terraform destroy -auto-approve \
          -var-file=environments/${{ github.event.inputs.environment }}.tfvars